const db = require('../config/connection');
const { Item, Look } = require('../models');

db.once('open', async () => {
  // clean database
  await Item.deleteMany({});
  await Look.deleteMany({});

  // Create Items
  const items = await Item.insertMany([
    {
      title: 'Revolt Free',
      description: 'Comfortable and stylish shoes.',
      image: ['/images/blacktrainer.jpg', '/images/blacktrainer2.jpg'],
      price: 60,
      discountedPrice: 60,
      stock: 30,
      colour: 'black',
      category: 'Men',
      featured: true,
    },
    {
      title: 'Sandstorm Belt',
      description: 'Brown thick set faux-leather belt.',
      image: ['/images/brownbelt.jpg', '/images/brownbelt1.jpg'],
      price: 35,
      discountedPrice: 27,
      stock: 20,
      colour: 'brown',
      category: 'Men',
    },
    {
      title: 'Moonlight Monochrome Shirt',
      description: 'Grayscale monochrome shirt. 100% cotton.',
      image: ['/images/checkshirt.jpg'],
      price: 45,
      discountedPrice: 45,
      stock: 25,
      colour: 'grey',
      category: 'Men',
      featured: true,
    },
    {
      title: 'Spring Fling Heels',
      description: 'Bright floral heels.',
      image: ['/images/flowerheels.jpg'],
      price: 30,
      discountedPrice: 20,
      stock: 15,
      colour: 'blue',
      category: 'Women',
    },
    {
      title: 'Heartbreak T-Shirt',
      description: 'Light white cotton t-shirt with faded black broken-heart logo. Screen printed with natural dye.',
      image: ['/images/heartbreakt.jpg'],
      price: 20,
      discountedPrice: 10,
      stock: 15,
      colour: 'white',
      category: 'Men',
    },
    {
      title: 'Osaka T-Shirt',
      description: 'White and blue t-shirt with large lucky-cat design. 100% cotton. ',
      image: ['/images/kiikiiluckycat.jpg'],
      price: 30,
      discountedPrice: 20,
      stock: 15,
      colour: 'blue',
      category: 'Men',
    },
    {
      title: 'Classics',
      description: 'Stonewashed denim skinny fit jeans.',
      image: ['/images/levijeans.jpg', '/images/levijeans1.jpg'],
      price: 55,
      discountedPrice: 38,
      stock: 15,
      colour: 'blue',
      category: 'Men',
    },
    {
      title: 'Cruz Oversized Sweater',
      description: 'Soft, loose, overwized boyfriend sweater. Perfect for snuggling up.',
      image: ['/images/orangesweater.jpg'],
      price: 35,
      discountedPrice: 35,
      stock: 15,
      colour: 'orange',
      category: 'Women',
    },
    {
      title: 'Dusty Dancer Leggings',
      description: 'Dusty pink loose leggings with tapered ankle.',
      image: ['/images/pinktrousers.jpg'],
      price: 75,
      discountedPrice: 49,
      stock: 15,
      colour: 'pink',
      category: 'Women',
    },
    {
      title: 'AK-720 Gliders',
      description: 'Slim black RayBan sunglasses, slips right in the pocket.',
      image: ['/images/raybans.jpg'],
      price: 80,
      discountedPrice: 65,
      stock: 15,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'Summer Breeze Dress',
      description: 'Virbant flowing red dress with eye-catching petal pattern.',
      image: ['/images/reddress.jpg'],
      price: 50,
      discountedPrice: 50,
      stock: 15,
      colour: 'red',
      category: 'Women',
      featured: true,
    },
    {
      title: 'SeaSkimmer Timepiece',
      description: 'Suave and stylish Seiko watch, because your time is important.',
      image: ['/images/seikowatch.jpg'],
      price: 75,
      discountedPrice: 75,
      stock: 70,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'Winter Wonderland Coat',
      description: 'Warm woolen coat with wraparound belt. 100% cashmere.',
      image: ['/images/testlook1.jpg'],
      price: 55,
      discountedPrice: 55,
      stock: 40,
      colour: 'blue',
      category: 'Women',
    },
    {
      title: 'Rose-Tinted Purse',
      description: 'Dusty pink rose half-moon purse with gold zipper.',
      image: ['/images/testlook2.jpg'],
      price: 30,
      discountedPrice: 30,
      stock: 40,
      colour: 'pink',
      category: 'Women',
    },
    {
      title: 'Chunky Swinging Boots',
      description: 'White chunky calf-length boots with square toe.',
      image: ['/images/testlook3.jpg'],
      price: 45,
      discountedPrice: 45,
      stock: 60,
      colour: 'white',
      category: 'Women',
    },
    {
      title: 'Pinstripe Trousers',
      description: 'Long flared trousers with black and white pinstripes.',
      image: ['/images/pinstripeflares1.jpg', '/images/pinstripeflares2.jpg'],
      price: 50,
      discountedPrice: 50,
      stock: 30,
      category: 'Women',
      colour: 'multi',
      featured: true,
    },
    {
      title: 'Vinyl Shoulder Bag',
      description: 'Red square vinyl handbag with detachable strap.',
      image: ['/images/redbag.jpg', '/images/redhandbag.jpg'],
      price: 35,
      discountedPrice: 28,
      stock: 30,
      colour: 'red',
      category: 'Women',
    },
    {
      title: 'Off-Shoulder Crop Top',
      description: 'White off-shoulder cotton crop top for those sometimes-sunny days.',
      image: ['/images/whitetop1.jpg', '/images/whitetop2.jpg'],
      price: 30,
      discountedPrice: 30,
      stock: 40,
      colour: 'white',
      category: 'Women',
    },
    {
      title: 'Cuffed Jeans',
      description: 'Faded green jeans with optional cuff.',
      image: ['/images/greenjeans1.jpg', '/images/greenjeans2.jpg'],
      price: 60,
      discountedPrice: 60,
      stock: 40,
      colour: 'green',
      category: 'Men',
    },
    {
      title: 'Funky Faded Tribal Fleece',
      description: 'Faded vintage style fleece with tribal pattern.',
      image: ['/images/tribalfleece1.jpg', '/images/tribalfleece2.jpg'],
      price: 55,
      discountedPrice: 55,
      stock: 20,
      colour: 'purple',
      category: 'Men',
      featured: true,
    },
    {
      title: 'GTA V T-Shirt',
      description: 'Classic GTA V cotton t-shirt. Screen printed.',
      image: ['/images/gta51.jpg', '/images/gta52.jpg'],
      price: 30,
      discountedPrice: 30,
      stock: 50,
      colour: 'white',
      category: 'Men',
    },
    {
      title: 'Vintage Circle Shades',
      description: 'Classic chic circle sunglasses frames.',
      image: ['/images/roundsunnies1.jpg', '/images/roundsunnies2.jpg'],
      price: 25,
      discountedPrice: 17,
      stock: 30,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'Old-Skool Vasrity Jacket',
      description: 'Red vinyl American style zip-up varsity jacket with white stripe detail.',
      image: ['/images/redvarsity1.jpg', '/images/redvarsity2.jpg'],
      price: 65,
      discountedPrice: 65,
      stock: 30,
      colour: 'red',
      category: 'Men',
      featured: true,
    },
    {
      title: 'Petalhead Rose Cap',
      description: 'Black canvas peaked cap with embroidered red rose design.',
      image: ['/images/redrosehat1.jpg', '/images/redrosehat2.jpg'],
      price: 25,
      discountedPrice: 25,
      stock: 30,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'Vans Classic Sk8-Hi',
      description: 'Durable and stylish black hi-top skate shoes with white racing stripes.',
      image: ['/images/vanssk81.jpg', '/images/vanssk82.jpg'],
      price: 75,
      discountedPrice: 75,
      stock: 30,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'High Flyers',
      description: 'Gold rimmed aviator shades.',
      image: ['/images/goldglasses1.jpg', '/images/goldglasses2.jpg'],
      price: 60,
      discountedPrice: 60,
      stock: 30,
      colour: 'black',
      category: 'Men',
    },
    {
      title: 'Button Down The Hatches',
      description: 'Blue cotton shirt with suave button-down collar.',
      image: ['/images/bluebuttonshirt1.jpg', '/images/bluebuttonshirt2.jpg'],
      price: 40,
      discountedPrice: 22,
      stock: 50,
      colour: 'blue',
      category: 'Men',
    },
    {
      title: 'Rusty Diamond Biker Jacket',
      description: 'Deep brown organically-tanned faux-leather biker jacket with side zip and collar studs.',
      image: ['/images/brownbiker1.jpg', '/images/brownbiker2.jpg'],
      price: 80,
      discountedPrice: 80,
      stock: 50,
      colour: 'blue',
      category: 'Men',
      featured: true,
    },
    {
      title: 'Sunset Rodeo Boots',
      description: 'Soft brown suede thigh-high boots - yee-ha cowgirl!',
      image: ['/images/brownboots1.jpg', '/images/brownboots2.jpg'],
      price: 70,
      discountedPrice: 70,
      stock: 50,
      colour: 'brown',
      category: 'Women',
    },
    {
      title: 'Daisy Duke Cuffed Shorts',
      description: 'Short and sweet, white denim shorts with optional cuff. Natural bleach.',
      image: ['/images/whiteshorts1.jpg', '/images/whiteshorts2.jpg', '/images/whiteshorts3.jpg'],
      price: 25,
      discountedPrice: 25,
      stock: 50,
      colour: 'white',
      category: 'Women',
    },
    {
      title: 'Vintage Chevron Sweater',
      description: 'Tan and black vintage chevron sweater. Open weave. 100% argyle wool.',
      image: ['/images/chevronsweater1.jpg', '/images/chevronsweater2.jpg', '/images/chevronsweater3.jpg'],
      price: 45,
      discountedPrice: 45,
      stock: 40,
      colour: 'brown',
      category: 'Women',
      featured: true,
    },
    {
      title: 'Denim Oversized Shorty Dress',
      description: 'Oversized softened denim dress. Treated denim to avoid colour run.',
      image: ['/images/denimcoat1.jpg', '/images/denimcoat2.jpg'],
      price: 55,
      discountedPrice: 55,
      stock: 40,
      colour: 'blue',
      category: 'Women',
    },
    {
      title: 'Gilded Age Choker',
      description: '24k gold-plated triple-thread choker with metallic clasp.',
      image: ['/images/goldchoker1.jpg', '/images/goldchoker2.jpg'],
      price: 100,
      discountedPrice: 100,
      stock: 35,
      colour: 'gold',
      category: 'Women',
    },
    {
      title: 'Paradise Hair Flowers',
      description:
        'Colourful eye-catching flower clips. Waterproof and suitable for all hair types. 50/50 cotton-polyester blend',
      image: ['/images/hairflowers1.jpg', '/images/hairflowers2.jpg'],
      price: 20,
      discountedPrice: 20,
      stock: 55,
      colour: 'multi',
      category: 'Women',
      featured: true,
    },
    {
      title: 'Blush Sweater',
      description: 'Sofy, comfy pink sweater. 100% cotton.',
      image: ['/images/pinksweater1.jpg', '/images/pinksweater2.jpg'],
      price: 35,
      discountedPrice: 24,
      stock: 55,
      colour: 'pink',
      category: 'Men',
    },
    {
      title: 'Ripped It Up',
      description: 'Sylisishly slashed blue stonewashed denim jeans',
      image: ['/images/rippedjeans1.jpg', '/images/rippedjeans2.jpg'],
      price: 60,
      discountedPrice: 42,
      stock: 55,
      colour: 'blue',
      category: 'Men',
    },
    {
      title: 'Summer Of Love Sunglasses',
      description: 'Retro heart-shaped sunglasses with gold-plated rim and pink lenses - rose-tint your world!',
      image: ['/images/heartglasses.jpg', '/images/heartglasses1.jpg'],
      price: 30,
      discountedPrice: 30,
      stock: 45,
      colour: 'pink',
      category: 'Unisex',
      featured: true,
    },
    {
      title: 'Catch Of The Day Socks',
      description: 'Black large-weave fishnet calf-length socks',
      image: ['/images/fishnetsocks1.jpg', '/images/fishnetsocks2.jpg'],
      price: 25,
      discountedPrice: 25,
      stock: 45,
      colour: 'black',
      category: 'Unisex',
      featured: true,
    },
    {
      title: 'Played A Blinder Waistcoat',
      description: 'Sophisticated midnight blue button-up waistcoat with pocket chain.',
      image: ['/images/bluewaistcoat1.jpg', '/images/bluewaistcoat2.jpg'],
      price: 80,
      discountedPrice: 80,
      stock: 45,
      colour: 'blue',
      category: 'Men',
    },
    {
      title: 'The Mistress Pleated Skirt',
      description: 'Brown large pleat high-waisted long skirt.',
      image: ['/images/pleatskirt1.jpg', '/images/pleatskirt2.jpg'],
      price: 45,
      discountedPrice: 45,
      stock: 45,
      colour: 'brown',
      category: 'Women',
    },
    {
      title: 'Counter Vanity Clutch',
      description: 'Chunky circular cream clutch with detachable strap. Vegan leather.',
      image: ['/images/circlebag1.jpg', '/images/circlebag2.jpg'],
      price: 50,
      discountedPrice: 50,
      stock: 45,
      colour: 'white',
      category: 'Women',
    },
    {
      title: 'Vintage 70s Scarf',
      description: 'Retro style silk scarf with tootal pattern.',
      image: ['/images/silkscarf1.jpg', '/images/silkscarf2.jpg', '/images/silkscarf3.jpg'],
      price: 40,
      discountedPrice: 33,
      stock: 45,
      colour: 'multi',
      category: 'Women',
    },
    {
      title: 'Scruffster Trousers',
      description: 'Baggy overall-style high-waisted canvas trousers with optional cuff.',
      image: ['/images/overalltrousers1.jpg', '/images/overalltrousers2.jpg'],
      price: 65,
      discountedPrice: 65,
      stock: 45,
      colour: 'black',
      category: 'Women',
    },
    {
      title: 'Mesh Cutout Leotard',
      description: 'Black leotard with mismatch mesh geometric cut-out.',
      image: ['/images/meshleotard1.jpg', '/images/meshleotard2.jpg'],
      price: 40,
      discountedPrice: 40,
      stock: 45,
      colour: 'black',
      category: 'Women',
    },
    {
      title: 'Stick Up Stilettos',
      description: 'White glossy patent stiletto heels with pointed toe.',
      image: ['/images/whitestiletto1.jpg', '/images/whitestiletto2.jpg', '/images/whitestiletto3.jpg'],
      price: 45,
      discountedPrice: 45,
      stock: 45,
      colour: 'white',
      category: 'Women',
    },
  ]);

  console.log(items);
  console.log('items seeded');

  // await Look.create(lookData);
  const looks = await Look.insertMany([
    {
      influencer: 'Selina',
      image: '/images/look1.jpg',
      description:
        'Being swept away by the beautiful pigeons outside the cathedral. @Dior @Chanel @Balenciaga #WindyFashion',
      items: [items[12]._id, items[13]._id, items[14]._id],
    },
    {
      influencer: 'AlwaysAnika',
      image: '/images/pinstripes.jpg',
      description:
        'Careful not to say my name 3 times! Love me some neon lighting #GoodVibesOnly @Missguided @Chanel @BooHoo',

      items: [items[15]._id, items[16]._id, items[17]._id],
    },
    {
      influencer: 'DustyDylan',
      image: '/images/influencer3.jpg',
      description:
        'Surveying my kingdom. Everything the light touches... #shabbychic #retrovibes @BooHooMan @Levis @JPGaultier @RayBans',
      items: [items[18]._id, items[19]._id, items[20]._id, items[21]._id],
    },
    {
      influencer: 'JustJared',
      image: '/images/influencer4.jpg',
      description:
        'Always catch me out on the board in some classic threads. @Vans @TommyHilfiger #skatestyle #skater4life',
      items: [items[22]._id, items[23]._id, items[24]._id],
    },
    {
      influencer: 'Darius Daily',
      image: '/images/influencer5.jpg',
      description:
        'Swish, suave...always looking both ways before crossing the road LOL! #DrippingInTheGucc @Gucci @RayBan ',
      items: [items[25]._id, items[26]._id, items[27]._id],
    },
    {
      influencer: 'Coastal Cathy',
      image: '/images/influencer6.jpg',
      description:
        'Finding some peace and calm among the waves and pebbles. Such a soothing, ancient sound. #blessed #innerpeace @Oasis @Fendi @DKNY',
      items: [items[28]._id, items[29]._id, items[30]._id],
    },
    {
      influencer: 'LeelaLooksLovely',
      image: '/images/denim-dress.jpg',
      description:
        'Being beautiful amid the hustle and bustle of big city living. Get some colour up in there! #casualbling @Levis @HareyNichols @ASOS',
      items: [items[31]._id, items[32]._id, items[33]._id],
    },
    {
      influencer: 'InZaynInTheMemeBrain',
      image: '/images/influencer7.jpg',
      description:
        'Just catching my breath, try not to catch feelings. Real men wear PINK! @Moschino @Levis @VivienneWestwood @RayBan',
      items: [items[34]._id, items[35]._id, items[36]._id, items[37]._id],
    },
    {
      influencer: 'The Dapperest',
      image: '/images/influencer8.jpg',
      description: 'Mystery, intrigue...I call this pose "Where did I leave my keys?" #therealenigma @Armani @Seiko',
      items: [items[38]._id, items[11]._id],
    },
    {
      influencer: 'WhatIsCharlotteWearing?',
      image: '/images/influencer9.jpg',
      description: 'Had a beautiful time away with family and friends, slightly exhausted now! @Hermes @Fendi @DKNY',
      items: [items[39]._id, items[40]._id, items[41]._id],
    },
    {
      influencer: 'Alisha After Dark',
      image: '/images/influencer10.jpg',
      description: 'The best lighting is always in the weirdest places! #neonservices @FCUK @ASOS @Balenciaga',
      items: [items[42]._id, items[43]._id, items[44]._id],
    },
  ]);
  console.log(looks);
  console.log('Looks data seeded!');
  console.log('all done!');
  process.exit(0);
});
